version: "2"

services:

  node:
    image: "node:5"
    ports:
      - "3000:3000"
    volumes:
      - ./:/code
    working_dir: /code
    tty: true
    stdin_open: true
    command: sh -c 'npm install && npm start'
