version: "2"

services:

  node:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/code
    working_dir: /code
    tty: true
    stdin_open: true
    command: sh -c 'yarn && yarn start'
